name: OpenVPN Connection
author: Leukeleu B.V.
description: Create a VPN connection to a remote server
branding:
  icon: lock
  color: orange
runs:
  using: "node20"
  main: "main.js"
  post: "cleanup.js"
