name: OpenVPN Connection
author: Leukeleu B.V.
description: Create a VPN connection to a remote server
branding:
  icon: lock
  color: orange
inputs:
  ovpn_profile:
    description: The contents of the OpenVPN profile file
    required: true
  ovpn_username:
    description: The username for the OpenVPN connection
    required: true
  ovpn_password:
    description: The password for the OpenVPN connection
    required: true
runs:
  using: "node20"
  main: "main.js"
  post: "cleanup.js"
